language: rust
rust:
  # The nightly version has to be locked since a build of clippy isn't always
  # available for the current nightly.
  - nightly-2019-12-19

os:
  - linux

cache: cargo

addons:
  apt:
    sources:
      - sourceline: 'ppa:wireguard/wireguard'
    packages:
      - linux-headers-$(uname -r)
      - wireguard

stages:
  - build
  - check

jobs:
  include:

    - stage: build
      script:
        - cargo build --verbose

    - stage: check
      name: Clippy
      script:
        - rustup component add clippy
        - cargo clippy --all-targets --all-features

    - stage: check
      name: rustfmt
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

    - stage: check
      name: Test
      script:
        # Necessary for tests that read/write to the configuration folder.
        - sudo mkdir -p /var/lib/wg-web-server
        - sudo chown $(whoami) /var/lib/wg-web-server

        - cargo build --tests --verbose
        # Give compiled tests the ability to set and read WireGuard devices. Otherwise
        # they will likely fail with access/permission errors.
        - find ./target/debug -maxdepth 1 -type f -executable | xargs -n 1 sudo setcap CAP_NET_ADMIN=+eip
        - cargo test --verbose
